### ISSUE TITLE
Definitie oneOf met discriminator niet correct voor tenaamstelling.persoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#280]
De manier waarop de discriminator is gedefinieerd voor de oneOf op de tenaamstelling persoon is niet correct.

Er staat nu:
```
Tenaamstelling:
   ...
      persoon:
          oneOf:
            - $ref: "#/components/schemas/PersoonCompact"
            - $ref: "#/components/schemas/NietNatuurlijkPersoonCompact"
```

Hier ontbreekt de discriminator.

```
    AbstractPersoonCompact:
      type: object
      description: "Deze constructie is toegevoegd om te voorkomen dat het persoon-element uittenaamstelling met een oneOf zou moeten worden gedefinieerd. Dat levert problemen op bij codegeneratie. "
      properties:
        identificatie:
          title: identificatie
          type: string
      discriminator:
        propertyName: type
```

Hier is een discriminator keyword opgenomen die verwijst naar een property "type". Dit keyword had in Tenaamstelling bij persoon moeten zijn opgenomen (dus bij de oneOf definitie).

Daarnaast is er geen property type gedefinieerd. Ik zou ook voorstellen een iets meer beschrijvende discriminator property naam te gebruiken, zoals objectType of persoonType.

Ik had dus verwacht:
```
Tenaamstelling:
   ...
      persoon:
          oneOf:
            - $ref: "#/components/schemas/PersoonCompact"
            - $ref: "#/components/schemas/NietNatuurlijkPersoonCompact"
         discriminator:
            propertyName: persoonType
```
en
```
    AbstractPersoonCompact:
      type: object
      description: "Deze constructie is toegevoegd om te voorkomen dat het persoon-element uittenaamstelling met een oneOf zou moeten worden gedefinieerd. Dat levert problemen op bij codegeneratie. "
      properties:
        identificatie:
          title: identificatie
        persoonType: string
          type: 
            type: "string"
            enum:
            - "natuurlijkpersoon"
            - "nietnatuurlijkpersoon"
```
