### ISSUE TITLE
adres__huisnummer gedefinieerd als integer met pattern

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#477]
```
- in: query
          name: adres__huisnummer
          description: "Het huisnummer van het adres van de objectlocatie van de kadastraal onroerende zaak"
          required: false
          schema:
            type: integer
            pattern: "^[1-9][0-9]{0,4}$"
```

Een pattern heeft betrekking op een string, niet op een integer. Dus moet hier geen pattern gedefinieerd worden.

Het is nu geïmplementeerd met minimum: 1 en maximum: 99999. Dat moet m.i. dan ook worden toegevoegd aan de specificaties.
