### ISSUE TITLE
Er wordt fout gecontroleerd op de reguliere expressie van kadastraleAanduiding

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#875]
**Beschrijf de bug**
Als ik een bevraging doe op de bron (https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1 in mijn geval) dan mag ik zonder issue de volgende kadastraleAanduiding gebruiken: 's-Gravenhage N 8272 A3. Echter dit is waar de bron verkeerd gaat en de specificaties dus ook niet correct hanteert.

In de specificaties kan worden terug gevonden het volgende onder het pad '/kadastraalonroerendezaken': 
```
- name: kadastraleAanduiding
        in: query
        description: |
          Kadastrale aanduiding is een unieke aanduiding van een onroerende zaak. De volgorde waarin deze string wordt opgebouwd is
          - [Kadastrale gemeente](http://www.kadaster.nl/schemas/waardelijsten/KadastraleGemeente/).
          - sectie, 1 of 2 hoofdletters
          - perceelnummer, 1 tot 5 cijfers
          - appartementsrechtVolgnummer, Hoofdletter A gevolgd door 1 tot 4 cijfers (optioneel)
          gescheiden door een spatie"
        schema:
          pattern: ^([a-zA-Z0-9'][a-zA-Z0-9' ,-]*[a-zA-Z0-9]) ([A-IK-Z]{1,2}) ([1-9][0-9]{0,4})(
            A[1-9][0-9]{0,3})?$
          type: string
          example: '''s Gravenhage C 1277 A3'
```

Hierin staat een reguliere expressie dat niet een waarde als ''s-Gravenhage N 8272 A3' zal accepteren, maar de bron vindt dit alsnog een valide waarde. Je zou hiermee kunnen concluderen dat er niet wordt gecontroleerd op de reguliere expressie controle, echter lijkt dit wel het geval te zijn gek genoeg. Als je de voorbeelden uit de 'Getting started' gebruikt (die tevens nog altijd verkeerd staan desondanks eerder meldingen) dan worden deze wel geweigerd onder de mom van deze reguliere expressie. Zoals bijv. bij 'Odoorn:717 N 2340'.

**Verwacht gedrag**
De bron dient de specificaties te hanteren zoals deze dat hoort te doen en niet uitzonderingen maakt of het een productie is of niet.

Deze reguliere expressie is überhaupt foutief volgens de beschrijving van de opbouw van een aanduiding en ook zeer eenvoudiger kan dan de huidige complexe notatie. Om deze twee vraagstukken los van elkaar te houden zal ik aanvullend nog hiervoor een aparte issue aanmaken.
